spring:
  profiles:
    active: local

logging:
  level:
    com.ll.mutbooks: debug


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: SA
    password:
